@baseUrl = http://127.0.0.1:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "test",
  "password": "test",
  "email": "test@test.com",
  "avatarColor": "red",
  "avatarImage": "data:text/plain;base64,SGVsbG8sIFdvcmxkIQ=="
}

###
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "test",
  "password": "test1"
}

###
GET {{baseUrl}}/{{urlPath}}/signout
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/currentuser
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/forgot-password
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "email": "test@test.com"
}

###
POST {{baseUrl}}/{{urlPath}}/reset-password/025695fd8699546f745e821ba449ceb95b2fed63
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "password": "test1",
  "confirmPassword": "test1"
}
